// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfo {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_name: ::prost::alloc::string::String,
}
/// 系统统计数据
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemMetrics {
    /// 内存占用
    #[prost(message, optional, tag = "1")]
    pub mem: ::core::option::Option<MemMetrics>,
    /// cpu占用
    #[prost(message, optional, tag = "2")]
    pub cpu: ::core::option::Option<CpuMetrics>,
    /// 磁盘占用
    #[prost(message, optional, tag = "3")]
    pub disk: ::core::option::Option<DiskMetrics>,
}
/// 内存占用详细数据
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MemMetrics {
    /// 总内存字节数
    #[prost(uint64, tag = "1")]
    pub total: u64,
    /// 可用内存字节数
    #[prost(uint64, tag = "2")]
    pub available: u64,
    /// 已使用字节数
    #[prost(uint64, tag = "3")]
    pub used: u64,
    /// 使用百分比
    #[prost(float, tag = "4")]
    pub usage: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CpuMetrics {
    /// cpu 使用百分比
    #[prost(float, tag = "1")]
    pub usage: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskMetrics {
    #[prost(message, repeated, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<DiskMetricsItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiskMetricsItem {
    /// 设备
    #[prost(string, tag = "1")]
    pub device: ::prost::alloc::string::String,
    /// 总字节数
    #[prost(uint64, tag = "2")]
    pub total: u64,
    /// 使用字节数
    #[prost(uint64, tag = "3")]
    pub used: u64,
}
