// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MemStat {
    /// 总内存字节数
    #[prost(uint64, tag = "1")]
    pub total: u64,
    /// 可用内存字节数
    #[prost(uint64, tag = "2")]
    pub available: u64,
    /// 已使用字节数
    #[prost(uint64, tag = "3")]
    pub used: u64,
    /// 使用百分比
    #[prost(float, tag = "4")]
    pub usage: f32,
    /// 所属节点
    #[prost(string, tag = "5")]
    pub uniq_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CpuStat {
    /// cpu 使用百分比
    #[prost(float, tag = "1")]
    pub usage: f32,
    /// 所属节点
    #[prost(string, tag = "2")]
    pub uniq_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiskStat {
    #[prost(string, tag = "1")]
    pub uniq_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub data: ::prost::alloc::vec::Vec<DiskStatItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DiskStatItem {
    /// 设备名
    #[prost(string, tag = "1")]
    pub device_name: ::prost::alloc::string::String,
    /// 总字节数
    #[prost(uint64, tag = "2")]
    pub total: u64,
    /// 使用字节数
    #[prost(uint64, tag = "3")]
    pub used: u64,
    /// 所属节点
    #[prost(string, tag = "4")]
    pub uniq_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfo {
    #[prost(message, optional, tag = "1")]
    pub mem: ::core::option::Option<MemStat>,
    #[prost(message, optional, tag = "2")]
    pub cpu: ::core::option::Option<CpuStat>,
    #[prost(message, optional, tag = "3")]
    pub disk: ::core::option::Option<DiskStat>,
}
