[package]
name = "genesis-common"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
[dependencies]
serde = "1.0.214"
serde_json = "1.0.132"
tokio = "1.41.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = {version="1.11.0",features=["v4","serde"]}
