[package]
name = "genesis-common"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = "1.41.0"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
